[package]
authors = ["Joep Meindertsma <joep@ontola.io>"]
description = "A simple `Server-Timing` header crate. No dependencies."
edition = "2021"
license = "MIT"
name = "simple-server-timing-header"
version = "0.1.0"

[dependencies]
